providers:
  - id: METLOOM
    collections: 
      - id: SNOTEL
        datetime: 2017-04-01/2021-04-23
        aoi_file: config/aoi/demo_landcover.json
        max_items: 3
        outdir: data/snotel_land_cover_north_america
        assets:
          - all
      - id: CDEC
        datetime: 2017-04-01/2021-04-23
        aoi_file: config/aoi/conus-expanded.json
        max_items: 3
        outdir: data/cdec_conus_expanded
        assets:
          - SWE

system:
  max_concurrent_extractions: 10
  log_level: INFO
  log_outdir: ./logs
