providers:
  - id: METLOOM
    collections: 
      - id: SNOTEL
        datetime: 2017-04-01/2021-04-23
        aoi_file: config/aoi/demo_landcover.json
        max_items: 3
        outdir: data/snotel_land_cover_north_america
        assets:
          - SWE
          - AIR TEMP
      - id: CDEC
        datetime: 2017-04-01/2021-04-23
        aoi_file: config/aoi/demo_landcover.json
        max_items: 3
        outdir: data/cdec_land_cover_north_america
        assets:
          - SWE

system:
  max_concurrent_extractions: 10
  max_download_attempts: 3
  log_level: INFO
  log_outdir: ./logs
  remove_existing_if_wrong_size: True
  query_asset_sizes: False
  dry_run: True
